### ISSUE TITLE
Request is missing required authentication credential

### ISSUE THREAD

**Issue by laicasaane** [microsoft/google-play-vsts-extension#388]
This issue has just happened to our Android pipelines today. It was fine yesterday.

```
##[error]Error: Failed to upload the bundle <app-file.aab>. Failed with message: GaxiosError: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at Gaxios._request (/<project-folder>/_work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.217.0/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/<project-folder>/_work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.217.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18) {
  response: [Object],
  config: [Object],
  code: 401,
  errors: [Array]
}
```

**Comment by lassana** [comment]
Same here:

```
Starting: Release ch.***.my***app to internal
==============================================================================
Task         : Google Play - Release
Description  : Release an app to the Google Play Store
Version      : 4.217.0
Author       : Microsoft Corporation
Help         : https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play
==============================================================================
Authenticated with Google Play and getting new edit
##[error]Error: Failed to upload the bundle /Users/runner/work/1/b/Release/ch.***.my***app-Signed.aab. Failed with message: GaxiosError: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at Gaxios._request (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.217.0/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.217.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18) {
  response: [Object],
  config: [Object],
  code: 401,
  errors: [Array]
}.
Finishing: Release ch.***.my***app to internal
```

 @LiliaSabitova any chances this be prioritized?  We are unable to publish a new Play Store update due to this issue.

**Comment by andreasgarvik** [comment]
This issue needs more attention, unable to publish to Google Play.

**Comment by allagerman** [comment]
Same here, we've started to see this issue starting Sep 14. It's on and off. There is no workaround besides retrying...Any suggestions hoe to resolve it?

**Comment by hsynaksu** [comment]
We also started seeing this error from time to time. It goes through after a couple of retries

**Comment by mlorenz2** [comment]
```
Starting: Android release
==============================================================================
Task         : Google Play - Release
Description  : Release an app to the Google Play Store
Version      : 4.226.0
Author       : Microsoft Corporation
Help         : https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play
==============================================================================
Authenticated with Google Play and getting new edit
##[error]Error: Failed to upload the bundle /Users/runner/work/1/s/build/app/outputs/bundle/release/**.aab. Failed with message: GaxiosError: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at Gaxios._request (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.226.0/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.226.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18) {
  response: [Object],
  config: [Object],
  code: 401,
  errors: [Array]
}.
```

Issue started this week on our side. Every 2nd build fails...

**Comment by johnklombard** [comment]
Same issue started this week.  ##[error]Error: Failed to upload the bundle D:/a/1/a/bundles/signed-qa-bundle.aab. Failed with message: GaxiosError: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.  Anyone know of a workarround?

**Comment by djonik1562** [comment]
I got the same error today. 
`2023-09-20T16:05:02.9010524Z ##[section]Запуск: Release ru.sedi.customer.apelsin to production
2023-09-20T16:05:02.9151817Z ==============================================================================
2023-09-20T16:05:02.9152167Z Task         : Google Play - Release
2023-09-20T16:05:02.9266383Z Description  : Release an app to the Google Play Store
2023-09-20T16:05:02.9266964Z Version      : 4.207.0
2023-09-20T16:05:02.9267247Z Author       : Microsoft Corporation
2023-09-20T16:05:02.9270396Z Help         : 
2023-09-20T16:05:02.9270756Z ==============================================================================
2023-09-20T16:05:05.6529647Z ##[warning]Input apkFile was set, but it will not be used in this action
2023-09-20T16:05:05.7881619Z Authenticated with Google Play and getting new edit
2023-09-20T16:05:08.0833696Z ##[error]Error: Failed to upload the bundle SeDi-Android-CustomerClient/flavor_apRelease/appid.aab. Failed with message: Error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project..
2023-09-20T16:05:08.1045987Z ##[section]Завершение: Release appid to production`

**Comment by DenisRumyantsev** [comment]
This issue is caused by an outage on the Google side. Implemented retries for this error. Duplicate of [this issue](https://github.com/microsoft/google-play-vsts-extension/issues/417). Closing it.
