### ISSUE TITLE
App Upload via google play extension failed

### ISSUE THREAD

**Issue by onkarmonks** [microsoft/google-play-vsts-extension#417]
Using Azure pipeline to upload Android App bundle to Play console but suddenly since yesterday started getting the below error

Starting: Release com.tatadigital.tcp to internal
==============================================================================
Task         : Google Play - Release
Description  : Release an app to the Google Play Store
Version      : 4.226.0
Author       : Microsoft Corporation
Help         : https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play
==============================================================================
Authenticated with Google Play and getting new edit
##[error]Error: Failed to upload the bundle /Users/runner/work/1/a/app/tata_neu_app/build/app/outputs/bundle/productionRelease/app-production-release-protected.aab. Failed with message: GaxiosError: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at Gaxios._request (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.226.0/node_modules/gaxios/build/src/gaxios.js:129:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.226.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18) {
  response: [Object],
  config: [Object],
  code: 401,
  errors: [Array]
}.

**Comment by DanielHead** [comment]
I am experiencing the same issue since Friday. This seems to be an issue Google's side.

Fastlane users are also experience the same problem - see: https://github.com/fastlane/fastlane/issues/21507

I have temporary worked around this for now by adding `retryCountOnTaskFailure: 5` to the GooglePlayRelease task

**Comment by AJH16** [comment]
We are also experiencing this issue.  Unfortunately we're still using a classic pipeline on this particular build so retryCountOnTaskFailure isn't an option for us.  Though this might prompt us to convert it.

**Comment by Reisclef** [comment]
We are also experiencing this error since Friday.

**Comment by sparkline** [comment]
Same for us, the workaround (retryCountOnTaskFailure) seems to be working

**Comment by danielbanks** [comment]
Same here for us!

**Comment by DenisRumyantsev** [comment]
@onkarmonks thanks for reporting this issue!
Could you enable pipeline debug logs and check if the retries (implemented for the upload error) work properly?

**Comment by DenisRumyantsev** [comment]
@DanielHead @AJH16 @Reisclef @sparkline @danielbanks Are you still experiencing this issue?

**Comment by DenisRumyantsev** [comment]
This issue is caused by an outage on the Google side. Implemented retries for this error. Duplicate of [this issue](https://github.com/microsoft/google-play-vsts-extension/issues/388). Closing it.
