### ISSUE TITLE
Error while publishing through GooglePlayRelease@4

### ISSUE THREAD

**Issue by FaustoNeves** [microsoft/google-play-vsts-extension#454]
Hello! Iam trying to update my app in Google Play Console through the GooglePlayRelease@4 task but Iam getting the following error:

```
Authenticated with Google Play and getting new edit
##[error]Error: Failed to upload the bundle /Users/runner/work/1/a/app/build/outputs/apk/debug/app-debug.apk. Failed with message: GaxiosError: We have failed to run 'bundletool build-apks' on this Android App Bundle. Please ensure your bundle is valid by running 'bundletool build-apks' locally and try again. Error message output: File 'BundleConfig.pb' was not found.
    at Gaxios._request (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.241.0/node_modules/gaxios/build/src/gaxios.js:129:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async JWT.requestAsync (/Users/runner/work/_tasks/GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27/4.241.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18) {
  response: [Object],
  config: [Object],
  code: 403,
  errors: [Array]
}.
```

I can generate the apk by the bundletool like the message is suggestin but I can't do the same with the pipeline. I have no idea what Iam doing wrong.
If more details are needed, please let me know

**Comment by vmapetr** [comment]
Hi @FaustoNeves thanks for reporting! 
We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by FaustoNeves** [comment]
> Hi @FaustoNeves thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

Hello @vmapetr. Thank you very much for the quick response. I understand. I look forward to your valuable help. Regards!

**Comment by Sebbs128** [comment]
Hi @vmapetr and others. I'm also seeing this in a newly created pipeline. It's becoming quite pressing to work out what the error is with Visual Studio App Center being shut down at the end of March 2025, and I and I'm sure many others needing to update our pipelines to push releases directly to Google Play.

The 403 would seem to indicate a permissions issue, but that's buried in the `errors` property which the logger isn't expanded by the logger. Even sorting that out would be a huge help.
